### this a distroless mutli stage docker file
# stage 1
FROM node:20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


# stage 2
FROM gcr.io/distroless/nodejs20
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src ./src
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["src/app.js"]